### ISSUE TITLE
Installation process heavily confusing

### ISSUE THREAD

**Issue by dishonest-truth** [Ocawesome101/minecraft-pipe-organ#2]
I get I install the v3.lua, but where do I **put the installed file?** What folder does it go in? Mods? Resource packs?

**Comment by Ocawesome101** [comment]
everything in the repo goes on a CC:T computer used to control the organ.  `play.lua` reads some settings and then plays music files and is the player you should use.  See [this video](https://youtu.be/N0ARUxaUosg) for more or less how to set it up.

you are correct that i did very little to make this user friendly.  maybe someday i'll improve that.
